# Generated by Django 4.1.7 on 2023-04-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(max_length=255, upload_to="hist_images")),
                (
                    "magnification",
                    models.IntegerField(
                        choices=[
                            (40, "40X"),
                            (100, "100X"),
                            (200, "200X"),
                            (400, "400X"),
                            (0, "UNKNOWN"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "stain",
                    models.CharField(
                        blank=True,
                        choices=[("H&E", "Hematoxylin eosin (H&E)"), ("", "Unknown")],
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rois",
                        to="machine_learning.label",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
